apiVersion: v1
items:
- apiVersion: logging.openshift.io/v1
  kind: ClusterLogging
  metadata:
    creationTimestamp: "2019-11-04T17:18:02Z"
    generation: 1
    name: instance
    namespace: openshift-logging
    resourceVersion: "58539"
    selfLink: /apis/logging.openshift.io/v1/namespaces/openshift-logging/clusterloggings/instance
    uid: 0ea42806-ff27-11e9-be69-06e29302fe30
  spec:
    collection:
      logs:
        fluentd: {}
        type: fluentd
    curation:
      curator:
        nodeSelector: 
          node-role.kubernetes.io/infra: ''
        schedule: 30 3 * * *
      type: curator
    logStore:
      elasticsearch:
        nodeCount: 2
        nodeSelector: 
          node-role.kubernetes.io/infra: ''
        redundancyPolicy: SingleRedundancy
        resources:
          requests:
            cpu: 500m
            memory: 4Gi
        storage:
          size: 20G
          storageClassName: gp2
      type: elasticsearch
    managementState: Managed
    visualization:
      kibana:
        nodeSelector: 
          node-role.kubernetes.io/infra: ''
        replicas: 1
      type: kibana
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
